name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

          # node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: ls build

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: bld-artifact-${{ github.sha }} # optional, default is artifact
          path: build/

          retention-days: 2
  deployment-to-test:
    runs-on: ubuntu-latest
    environment: test/test
    steps:
      - name: deploy
        run: echo deploy to test/test
      - name: deploy2
        run: echo deploy to test/test

  deployment-to-prod-e1:
    runs-on: ubuntu-latest
    environment: prod/east-1
    steps:
      - name: deploy
        run: echo deploy to prod/east-1
      - name: deploy2
        run: echo deploy to prod/east-1
  deployment-to-prod-s2:
    runs-on: ubuntu-latest
    environment: prod/south-2
    steps:
      - name: deploy
        run: echo deploy to prod/south-2
      - name: deploy2
        run: echo deploy to prod/south-2
