name: Deployment

concurrency: test1

on:
  workflow_dispatch:
  
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: test1
    steps:
      - name: deploy
        run: echo deploy to test1
        # ...deployment-specific steps
