name: Deployment

concurrency: test/test

on:
  workflow_dispatch:
  
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: test/test
    steps:
      - name: deploy
        run: echo deploy to test/test
        # ...deployment-specific steps
